// mklang keeps the translations in step with the code.
//
//	go run ./cmd/mklang keys <repo>  collect the UI strings (every DC.t('…') literal in shared/web/js) and the
//	                                  backend messages (internal/i18n/backend-keys.json) into internal/i18n/source.json
//	go run ./cmd/mklang js <repo>    write shared/web/js/lang/<CODE>.js from internal/i18n/lang/<CODE>.json
//	                                  (UI strings only) and report what each language is missing
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// DC.t('…' or "…" as the first argument; the key must be a plain literal
var callRe = regexp.MustCompile(`DC\.t\(\s*('(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*")`)

type source struct {
	UI      []string `json:"ui"`
	Backend []string `json:"backend"`
}

func unquote(lit string) string {
	body := lit[1 : len(lit)-1]
	var b strings.Builder
	for i := 0; i < len(body); i++ {
		c := body[i]
		if c == '\\' && i+1 < len(body) {
			i++
			switch body[i] {
			case 'n':
				b.WriteByte('\n')
			case 't':
				b.WriteByte('\t')
			default:
				b.WriteByte(body[i])
			}
			continue
		}
		b.WriteByte(c)
	}
	return b.String()
}

func uiKeys(root string) []string {
	seen := map[string]bool{}
	files, _ := filepath.Glob(filepath.Join(root, "shared", "web", "js", "*.js"))
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			continue
		}
		for _, m := range callRe.FindAllStringSubmatch(string(b), -1) {
			seen[unquote(m[1])] = true
		}
	}
	return sorted(seen)
}

func sorted(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func writeJSON(p string, v any) {
	b, _ := json.MarshalIndent(v, "", "\t")
	if err := os.WriteFile(p, append(b, '\n'), 0644); err != nil {
		panic(err)
	}
}

func main() {
	if len(os.Args) < 3 {
		fmt.Fprintln(os.Stderr, "usage: mklang keys|js <repo root>")
		os.Exit(2)
	}
	root := os.Args[2]
	dir := filepath.Join(root, "daemon", "internal", "i18n")
	switch os.Args[1] {
	case "keys":
		var backend []string
		if b, err := os.ReadFile(filepath.Join(dir, "backend-keys.json")); err == nil {
			json.Unmarshal(b, &backend)
		}
		src := source{UI: uiKeys(root), Backend: backend}
		writeJSON(filepath.Join(dir, "source.json"), src)
		fmt.Printf("%d UI strings, %d backend messages\n", len(src.UI), len(src.Backend))
	case "js":
		ui := uiKeys(root)
		files, _ := filepath.Glob(filepath.Join(dir, "lang", "*.json"))
		for _, f := range files {
			code := strings.TrimSuffix(filepath.Base(f), ".json")
			var m map[string]string
			b, err := os.ReadFile(f)
			if err != nil || json.Unmarshal(b, &m) != nil {
				fmt.Printf("%s: unreadable\n", code)
				continue
			}
			out := map[string]string{}
			missing := 0
			for _, k := range ui {
				if v := m[k]; v != "" {
					out[k] = v
				} else {
					missing++
				}
			}
			js, _ := json.Marshal(out)
			content := "/* Generated by daemon/cmd/mklang from daemon/internal/i18n/lang/" + code + ".json. Do not edit. */\nwindow.DC_DICT = " + string(js) + ";\n"
			if err := os.WriteFile(filepath.Join(root, "shared", "web", "js", "lang", code+".js"), []byte(content), 0644); err != nil {
				panic(err)
			}
			fmt.Printf("%s: %d/%d UI strings translated\n", code, len(out), len(ui))
		}
	}
}
